### ISSUE TITLE
tiara and whokaryote prediction discrepancy

### ISSUE THREAD

**Issue by shimbalama** [ibe-uw/tiara#5]
Hi.

From your docs/paper I assume that this size discrepancy is alarming? 

grep euk whokaryote_predictions_T.tsv | wc -l
220366

grep euk tiara_pred.txt | wc -l
3161

**Comment by santonow** [comment]
Hi,
It's difficult to determine this without the input data, but as I understand **whokaryote** uses **tiara** output as an input to some RF model. It also classifies to fewer classes than **tiara** does – **whokaroyte** does a binary eukaryote/prokaryote classification, whereas **tiara** differentiates between eukaryotes, bacteria, archaea, mitochondria and plastids. 

It might be the case that **whokaryote**'s RF model treats organellar sequences as eukaryotic ones and most of the sequences that **tiara** didn't treat as eukaryotic but **whokaryote** did are in fact organellar sequences. You could check how many lines are classified as organellar by **tiara** (`grep organelle tiara_pred.txt | wc -l`). 

Of course it's also possible that **tiara** made some mistakes on your dataset and **whokaryote** fixed those – I think it's one of the goals of this program to use an ensemble approach so better accuracy can be achieved. 

I might be able to take a look at the results if you provide me a sample of your sequences (in particular the ones that you think **tiara** wrongly classified as non-eukaryotic).

In any case, I didn't participate in the creation of **whokaryote**, so any questions related to this program in particular should probably be answered by the maintainers of **whokaryote**.

Thanks,
santonow

**Comment by shimbalama** [comment]
Thanks for the rapid replay. Just realized I raised this on the wrong repo. Apologies!
